# This is a simple Dockerfile to create an image which
# upon instantiation, outputs text in the classic
# tradition of "Hello World."

# Base the image on Ubuntu (latest)
FROM    ubuntu:latest

# Create a volume named "/persistent".  Anything stored in
# /persistent will be available across instances of this
# container.
#VOLUME  ["/store"]

# Set the default command to run when the container
# is launched.
CMD     /bin/sh
